# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flutter812

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrimagerepo01.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_49e20fdcec3f4e069dc756dd94571461 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_54aee9723f33418684bcdd9f7da5f357 }}
    - name: Lowercase the repo name and username
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrimagerepo01.azurecr.io/nodejs/sample:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flutter812'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3ac1e46e01b74c9190462558eeaa6053 }}
        images: 'acrimagerepo01.azurecr.io/nodejs/sample:${{ github.sha }}'
